export * from "./alert/alert.service";
export * from "./appoinment/appointment.service";
export * from "./auth/auth.service";
export * from "./dashboard/dashboard.service";
export * from "./doctor/doctor.service";
export * from "./encryption/encryption.service";
export * from "./http/http.service";
export * from "./lab-order/lab-order.service";
export * from "./loader/loader.service";
export * from "./medication/medication.service";
export * from "./medicine/medicine.service";
export * from "./patient/patient.service";
export * from "./prescription/prescription.service";
export * from "./signalR/signal-r.service";
export * from "./test-service/test.service";
export * from "./testCategory-service/test-category.service";
export * from "./token/token.service";
export * from "./user/user.service";
export * from "./vender/vendor.service";
export * from "./vital/vital.service";
export * from "./patient-test/patient-test.service";
export * from "./medicine-brand/medicine-brand.service"
export * from "./prescription/prescription.service"