export enum MedicationDosageEnum {
    Capsule = 1,
    Tablet = 2,
    Ml = 3,
    Mg = 4,
    IU = 5,
    Drop = 6,
    Tablespoon = 7,
    Teaspoon = 8,
    Unit = 9,
    Puff = 10,
    Sachet = 11,
    Injection = 12,
    DoseStep = 13,
    Dropper = 14,
    MlPerH = 15,
    UnitsPerKg = 16,
}

export const MedicationDosages: Array<{label: string, value: MedicationDosageEnum}> = [
    { label: 'Capsule(s)', value: MedicationDosageEnum.Capsule },
    { label: 'Tablet(s)', value: MedicationDosageEnum.Tablet },
    { label: 'ml', value: MedicationDosageEnum.Ml },
    { label: 'mg', value: MedicationDosageEnum.Mg },
    { label: 'IU', value: MedicationDosageEnum.IU },
    { label: 'Drop', value: MedicationDosageEnum.Drop },
    { label: 'Tablespoon', value: MedicationDosageEnum.Tablespoon },
    { label: 'Teaspoon', value: MedicationDosageEnum.Teaspoon },
    { label: 'Unit(s)', value: MedicationDosageEnum.Unit },
    { label: 'Puff(s)', value: MedicationDosageEnum.Puff },
    { label: 'Sachet', value: MedicationDosageEnum.Sachet },
    { label: 'Injection', value: MedicationDosageEnum.Injection },
    { label: 'Dose Step', value: MedicationDosageEnum.DoseStep },
    { label: 'Dropper', value: MedicationDosageEnum.Dropper },
    { label: 'ml/h', value: MedicationDosageEnum.MlPerH },
    { label: 'Units/kg', value: MedicationDosageEnum.UnitsPerKg },
];
