export enum MedicationRouteEnum {
    Oral = 1,
    Intramuscular = 2,
    Nasal = 3,
    Intravenous = 4,
    Topical = 5,
    Intraosseous = 6,
    Intrathecal = 7,
    Intraperitoneal = 8,
    Intradermal = 9,
    Nasogastric = 10,
    SubLingual = 11,
    PerRectum = 12,
    Subcutaneous = 13,
    PerVaginal = 14,
    Inhalation = 15,
    Intraoccular = 16,
  }
  
export const MedicationRoutes: Array<{label: string, value: MedicationRouteEnum}> = [
    { label: 'Oral', value: MedicationRouteEnum.Oral },
    { label: 'Intramuscular', value: MedicationRouteEnum.Intramuscular },
    { label: 'Nasal', value: MedicationRouteEnum.Nasal },
    { label: 'Intravenous', value: MedicationRouteEnum.Intravenous },
    { label: 'Topical', value: MedicationRouteEnum.Topical },
    { label: 'Intraosseous', value: MedicationRouteEnum.Intraosseous },
    { label: 'Intrathecal', value: MedicationRouteEnum.Intrathecal },
    { label: 'Intraperitoneal', value: MedicationRouteEnum.Intraperitoneal },
    { label: 'Intradermal', value: MedicationRouteEnum.Intradermal },
    { label: 'Nasogastric', value: MedicationRouteEnum.Nasogastric },
    { label: 'Sub Lingual', value: MedicationRouteEnum.SubLingual },
    { label: 'Per Rectum', value: MedicationRouteEnum.PerRectum },
    { label: 'Subcutaneous', value: MedicationRouteEnum.Subcutaneous },
    { label: 'Per Vaginal', value: MedicationRouteEnum.PerVaginal },
    { label: 'Inhalation', value: MedicationRouteEnum.Inhalation },
    { label: 'Intraoccular', value: MedicationRouteEnum.Intraoccular },
  ];