export enum MedicationInstructionEnum {
    BeforeBreakfast = 1,
    AfterBreakfast = 2,
    BeforeDinner = 3,
    AfterDinner = 4,
    EmptyStomach = 5,
    AtBedtime = 6,
    Immediately = 7,
    BeforeLunch = 8,
    AfterLunch = 9,
    BeforeMeal = 10,
    AfterMeal = 11,
    WhenRequired = 12,
    AsNeeded = 13,
    EverySixHours = 14,
    EveryFourHours = 15,
    EveryTwoHours = 16,
    EveryOneHour = 17,
    EveryOtherDay = 18,
    EveryTwoWeeks = 19,
    ThreeTimesAWeek = 20,
    TwoTimesAWeek = 21,
    OnceAWeek = 22,
    OnceAMonth = 23,
    OnceInTwoMonths = 24,
    OnceInThreeMonths = 25,
    ForItching = 26,
    ForSleep = 27,
    ForImprovingBloodDeficiency = 28,
    ForKidneys = 29,
    ForBreathingDifficulty = 30,
    ForKeepingCalm = 31,
    ForTransplant = 32,
    ForDiabetes = 33,
    ForBloodPressure = 34,
    ForDiarrhea = 35,
    ForSwelling = 36,
    ForMuscles = 37,
    ForNerves = 38,
    ForChestInfection = 39,
    ForPain = 40,
    ForIncreasingUrine = 41,
    ForIncreasingAppetite = 42,
    PRN = 43,
    ForIncreasingImmunity = 44,
    ForLightPain = 45,
    ForAbdominalGas = 46,
    STAT = 47,
    ForStomach = 48,
    ForSeverePain = 49,
    ForJointPain = 50,
    ForJoints = 51,
    ForUricAcid = 52,
    ForThyroid = 53,
    ForBladder = 54,
    ToKeepCalm = 55,
    ForFever = 56,
    ForMusclePain = 57,
    ForMuscleStrain = 58,
    SteroidMedicine = 59,
    ForStrengthOfJoints = 60,
    ToPreventUricAcidEffects = 61,
    ToReduceInflamation = 62,
    ToPreventFits = 63,
    ForBoneStrength = 64,
    BeforeDialysis = 65,
    AfterDialysis = 66,
    DuringDialysis = 67,
    AtTheStartOfDialysis = 68,
    ForHeadache = 69,
    ForPainInStomach = 70,
    ForAbdominalBloating = 71,
    ForBurningInChest = 72,
    ForChestPain = 73,
    VaccineToPreventHepatitisB = 74,
    VaccineToPreventFlu = 75,
    VaccineForPneumonia = 76,
    VaccineToPreventMeningitis = 77,
  }
  
export  const MedicationInstructions: Array<{label: string, value: MedicationInstructionEnum}> = [
    { label: 'Before Breakfast', value: MedicationInstructionEnum.BeforeBreakfast },
    { label: 'After Breakfast', value: MedicationInstructionEnum.AfterBreakfast },
    { label: 'Before Dinner', value: MedicationInstructionEnum.BeforeDinner },
    { label: 'After Dinner', value: MedicationInstructionEnum.AfterDinner },
    { label: 'Empty Stomach', value: MedicationInstructionEnum.EmptyStomach },
    { label: 'At Bedtime', value: MedicationInstructionEnum.AtBedtime },
    { label: 'Immediately', value: MedicationInstructionEnum.Immediately },
    { label: 'Before Lunch', value: MedicationInstructionEnum.BeforeLunch },
    { label: 'After Lunch', value: MedicationInstructionEnum.AfterLunch },
    { label: 'Before Meal', value: MedicationInstructionEnum.BeforeMeal },
    { label: 'After Meal', value: MedicationInstructionEnum.AfterMeal },
    { label: 'When Required', value: MedicationInstructionEnum.WhenRequired },
    { label: 'As Needed', value: MedicationInstructionEnum.AsNeeded },
    { label: 'Every Six Hours', value: MedicationInstructionEnum.EverySixHours },
    { label: 'Every Four Hours', value: MedicationInstructionEnum.EveryFourHours },
    { label: 'Every Two Hours', value: MedicationInstructionEnum.EveryTwoHours },
    { label: 'Every One Hour', value: MedicationInstructionEnum.EveryOneHour },
    { label: 'Every Other Day', value: MedicationInstructionEnum.EveryOtherDay },
    { label: 'Every Two Weeks', value: MedicationInstructionEnum.EveryTwoWeeks },
    { label: 'Three Times A Week', value: MedicationInstructionEnum.ThreeTimesAWeek },
    { label: 'Two Times A Week', value: MedicationInstructionEnum.TwoTimesAWeek },
    { label: 'Once A Week', value: MedicationInstructionEnum.OnceAWeek },
    { label: 'Once A Month', value: MedicationInstructionEnum.OnceAMonth },
    { label: 'Once In Two Months', value: MedicationInstructionEnum.OnceInTwoMonths },
    { label: 'Once In Three Months', value: MedicationInstructionEnum.OnceInThreeMonths },
    { label: 'For Itching', value: MedicationInstructionEnum.ForItching },
    { label: 'For Sleep', value: MedicationInstructionEnum.ForSleep },
    { label: 'For Improving Blood Deficiency', value: MedicationInstructionEnum.ForImprovingBloodDeficiency },
    { label: 'For Kidneys', value: MedicationInstructionEnum.ForKidneys },
    { label: 'For Breathing Difficulty', value: MedicationInstructionEnum.ForBreathingDifficulty },
    { label: 'For Keeping Calm', value: MedicationInstructionEnum.ForKeepingCalm },
    { label: 'For Transplant', value: MedicationInstructionEnum.ForTransplant },
    { label: 'For Diabetes', value: MedicationInstructionEnum.ForDiabetes },
    { label: 'For Blood Pressure', value: MedicationInstructionEnum.ForBloodPressure },
    { label: 'For Diarrhea', value: MedicationInstructionEnum.ForDiarrhea },
    { label: 'For Swelling', value: MedicationInstructionEnum.ForSwelling },
    { label: 'For Muscles', value: MedicationInstructionEnum.ForMuscles },
    { label: 'For Nerves', value: MedicationInstructionEnum.ForNerves },
    { label: 'For Chest Infection', value: MedicationInstructionEnum.ForChestInfection },
    { label: 'For Pain', value: MedicationInstructionEnum.ForPain },
    { label: 'For Increasing Urine', value: MedicationInstructionEnum.ForIncreasingUrine },
    { label: 'For Increasing Appetite', value: MedicationInstructionEnum.ForIncreasingAppetite },
    { label: 'PRN', value: MedicationInstructionEnum.PRN },
    { label: 'For Increasing Immunity', value: MedicationInstructionEnum.ForIncreasingImmunity },
    { label: 'For Light Pain', value: MedicationInstructionEnum.ForLightPain },
    { label: 'For Abdominal Gas', value: MedicationInstructionEnum.ForAbdominalGas },
    { label: 'STAT', value: MedicationInstructionEnum.STAT },
    { label: 'For Stomach', value: MedicationInstructionEnum.ForStomach },
    { label: 'For Severe Pain', value: MedicationInstructionEnum.ForSeverePain },
    { label: 'For Joint Pain', value: MedicationInstructionEnum.ForJointPain },
    { label: 'For Joints', value: MedicationInstructionEnum.ForJoints },
    { label: 'For Uric Acid', value: MedicationInstructionEnum.ForUricAcid },
    { label: 'For Thyroid', value: MedicationInstructionEnum.ForThyroid },
    { label: 'For Bladder', value: MedicationInstructionEnum.ForBladder },
    { label: 'To Keep Calm', value: MedicationInstructionEnum.ToKeepCalm },
    { label: 'For Fever', value: MedicationInstructionEnum.ForFever },
    { label: 'For Muscle Pain', value: MedicationInstructionEnum.ForMusclePain },
    { label: 'For Muscle Strain', value: MedicationInstructionEnum.ForMuscleStrain },
    { label: 'Steroid Medicine', value: MedicationInstructionEnum.SteroidMedicine },
    { label: 'For Strength Of Joints', value: MedicationInstructionEnum.ForStrengthOfJoints },
    { label: 'To Prevent Uric Acid Effects', value: MedicationInstructionEnum.ToPreventUricAcidEffects },
    { label: 'To Reduce Inflamation', value: MedicationInstructionEnum.ToReduceInflamation },
    { label: 'To Prevent Fits', value: MedicationInstructionEnum.ToPreventFits },
    { label: 'For Bone Strength', value: MedicationInstructionEnum.ForBoneStrength },
    { label: 'Before Dialysis', value: MedicationInstructionEnum.BeforeDialysis },
    { label: 'After Dialysis', value: MedicationInstructionEnum.AfterDialysis },
    { label: 'During Dialysis', value: MedicationInstructionEnum.DuringDialysis },
    { label: 'At The Start Of Dialysis', value: MedicationInstructionEnum.AtTheStartOfDialysis },
    { label: 'For Headache', value: MedicationInstructionEnum.ForHeadache },
    { label: 'For Pain In Stomach', value: MedicationInstructionEnum.ForPainInStomach },
    { label: 'For Abdominal Bloating', value: MedicationInstructionEnum.ForAbdominalBloating },
    { label: 'For Burning In Chest', value: MedicationInstructionEnum.ForBurningInChest },
    { label: 'For Chest Pain', value: MedicationInstructionEnum.ForChestPain },
    { label: 'Vaccine To Prevent Hepatitis B', value: MedicationInstructionEnum.VaccineToPreventHepatitisB },
    { label: 'Vaccine To Prevent Flu', value: MedicationInstructionEnum.VaccineToPreventFlu },
    { label: 'Vaccine For Pneumonia', value: MedicationInstructionEnum.VaccineForPneumonia },
    { label: 'Vaccine To Prevent Meningitis', value: MedicationInstructionEnum.VaccineToPreventMeningitis },
  ];
  