export enum MedicationFrequencyEnum {
    OnlyOnce = 1,
    OnceADay = 2,
    TwiceADay = 3,
    ThriceADay = 4,
    FourTimesADay = 5,
    BeforeBed = 6,
    EveryHour = 7,
    Every2Hours = 8,
    Every3Hours = 9,
    Every4Hours = 10,
    Every6Hours = 11,
    Every8Hours = 12,
    Every12Hours = 13,
    EveryOtherDay = 14,
    Every3Days = 15,
    OnceAWeek = 16,
    TwiceAWeek = 17,
    ThriceAWeek = 18,
    Every10Days = 19,
    Every15Days = 20,
    OnceAMonth = 21,
    Once3Months = 22,
    OnceAYear = 23,
    EveryMorning = 24,
    EveryEvening = 25,
    EveryNight = 26,
    IfNeeded = 27,
    BeforeBreakfast = 28,
    Continuously = 29,
    BeforeLunch = 30,
    AfterLunch = 31,
    BeforeMeal = 32,
    AfterMeal = 33,
    BeforeDinner = 34,
    AfterDinner = 35,
    AsAdvised = 36,
    TwiceAMonth = 37,
    AfterBreakfast = 38,
    BeforeBreakfastAndLunch = 39,
    BeforeLunchAndDinner = 40,
    BeforeBreakfastAndDinner = 41,
    AfterBreakfastAndLunch = 42,
    AfterLunchAndDinner = 43,
    AfterBreakfastAndDinner = 44,
    BeforeBreakfastLunchAndDinner = 45,
    AfterBreakfastLunchAndDinner = 46,
    AtNoon = 47,
    NoonAndEvening = 48,
    MorningEveningNight = 49,
    MorningAndNoon = 50,
    At6am10am2pm6pm10pm = 51,
    ThriceADayFor21DaysThenOnlyAtNightForNext2Months = 52,
    TwiceADayFor21DaysThenOnlyAtNightForNext2Months = 53,
    TwiceADayFor21DaysThenOnwardsForNextTwoMonthsTake1CapsuleBySkipping1Day = 54,
    TwiceAWeekAfterDialysis = 55,
    ThriceAWeekAfterDialysis = 56,
    AfterDialysisInDoubleLumen = 57,
    AtTheStartOfDialysis = 58,
    DuringDialysis = 59,
    BeforeDialysis = 60,
    FirstInjectionNowThenAfter1MonthNextAt2MonthsEnd3rdInjectionAt6MonthsEnd = 61,
    OnceInAYear = 62,
    OneInjectionNowNextAfterAMonth = 63,
    OneInjectionNowOneAfterAMonthNextAfter6Months = 64,
  }
  
export const MedicationFrequencies: Array<{label: string, value: MedicationFrequencyEnum}>= [
    { label: 'Only Once', value: MedicationFrequencyEnum.OnlyOnce },
    { label: 'Once a day', value: MedicationFrequencyEnum.OnceADay },
    { label: 'Twice a day', value: MedicationFrequencyEnum.TwiceADay },
    { label: 'Thrice a day', value: MedicationFrequencyEnum.ThriceADay },
    { label: 'Four times a day', value: MedicationFrequencyEnum.FourTimesADay },
    { label: 'Before Bed', value: MedicationFrequencyEnum.BeforeBed },
    { label: 'Every hour', value: MedicationFrequencyEnum.EveryHour },
    { label: 'Every 2 hours', value: MedicationFrequencyEnum.Every2Hours },
    { label: 'Every 3 hours', value: MedicationFrequencyEnum.Every3Hours },
    { label: 'Every 4 hours', value: MedicationFrequencyEnum.Every4Hours },
    { label: 'Every 6 hours', value: MedicationFrequencyEnum.Every6Hours },
    { label: 'Every 8 hours', value: MedicationFrequencyEnum.Every8Hours },
    { label: 'Every 12 hours', value: MedicationFrequencyEnum.Every12Hours },
    { label: 'Every Other day', value: MedicationFrequencyEnum.EveryOtherDay },
    { label: 'Every 3 Days', value: MedicationFrequencyEnum.Every3Days },
    { label: 'Once a week', value: MedicationFrequencyEnum.OnceAWeek },
    { label: 'Twice a week', value: MedicationFrequencyEnum.TwiceAWeek },
    { label: 'Thrice a week', value: MedicationFrequencyEnum.ThriceAWeek },
    { label: 'Every 10 Days', value: MedicationFrequencyEnum.Every10Days },
    { label: 'Every 15 Days', value: MedicationFrequencyEnum.Every15Days },
    { label: 'Once a Month', value: MedicationFrequencyEnum.OnceAMonth },
    { label: 'Once 3 Months', value: MedicationFrequencyEnum.Once3Months },
    { label: 'Once a Year', value: MedicationFrequencyEnum.OnceAYear },
    { label: 'Every Morning', value: MedicationFrequencyEnum.EveryMorning },
    { label: 'Every Evening', value: MedicationFrequencyEnum.EveryEvening },
    { label: 'Every Night', value: MedicationFrequencyEnum.EveryNight },
    { label: 'If needed', value: MedicationFrequencyEnum.IfNeeded },
    { label: 'Before Breakfast', value: MedicationFrequencyEnum.BeforeBreakfast },
    { label: 'Continuously', value: MedicationFrequencyEnum.Continuously },
    { label: 'Before Lunch', value: MedicationFrequencyEnum.BeforeLunch },
    { label: 'After Lunch', value: MedicationFrequencyEnum.AfterLunch },
    { label: 'Before Meal', value: MedicationFrequencyEnum.BeforeMeal },
    { label: 'After Meal', value: MedicationFrequencyEnum.AfterMeal },
    { label: 'Before Dinner', value: MedicationFrequencyEnum.BeforeDinner },
    { label: 'After Dinner', value: MedicationFrequencyEnum.AfterDinner },
    { label: 'As Advised', value: MedicationFrequencyEnum.AsAdvised },
    { label: 'Twice a month', value: MedicationFrequencyEnum.TwiceAMonth },
    { label: 'After Breakfast', value: MedicationFrequencyEnum.AfterBreakfast },
    { label: 'Before Breakfast and Lunch', value: MedicationFrequencyEnum.BeforeBreakfastAndLunch },
    { label: 'Before Lunch and Dinner', value: MedicationFrequencyEnum.BeforeLunchAndDinner },
    { label: 'Before breakfast and dinner', value: MedicationFrequencyEnum.BeforeBreakfastAndDinner },
    { label: 'After Breakfast and Lunch', value: MedicationFrequencyEnum.AfterBreakfastAndLunch },
    { label: 'After Lunch and Dinner', value: MedicationFrequencyEnum.AfterLunchAndDinner },
    { label: 'After breakfast and dinner', value: MedicationFrequencyEnum.AfterBreakfastAndDinner },
    { label: 'Before Breakfast, Lunch & Dinner', value: MedicationFrequencyEnum.BeforeBreakfastLunchAndDinner },
    { label: 'After Breakfast, Lunch & Dinner', value: MedicationFrequencyEnum.AfterBreakfastLunchAndDinner },
    { label: 'at noon', value: MedicationFrequencyEnum.AtNoon },
    { label: 'noon and evening', value: MedicationFrequencyEnum.NoonAndEvening },
    { label: 'morning, evening, night', value: MedicationFrequencyEnum.MorningEveningNight },
    { label: 'Morning and noon', value: MedicationFrequencyEnum.MorningAndNoon },
    { label: 'at 6 am, 10 am, 2pm, 6 pm, 10 pm', value: MedicationFrequencyEnum.At6am10am2pm6pm10pm },
    {
      label: 'Thrice a day for 21 days, then only at night for next 2 months',
      value: MedicationFrequencyEnum.ThriceADayFor21DaysThenOnlyAtNightForNext2Months,
    },
    {
      label: 'Twice a day for 21 days, then only at night for next 2 months',
      value: MedicationFrequencyEnum.TwiceADayFor21DaysThenOnlyAtNightForNext2Months,
    },
    {
      label: 'Twice a day for 21 days, then onwards for next two months take 1 capsule by skipping 1 day',
      value: MedicationFrequencyEnum.TwiceADayFor21DaysThenOnwardsForNextTwoMonthsTake1CapsuleBySkipping1Day,
    },
    { label: 'Twice a week after dialysis', value: MedicationFrequencyEnum.TwiceAWeekAfterDialysis },
    { label: 'Thrice a week after dialysis', value: MedicationFrequencyEnum.ThriceAWeekAfterDialysis },
    { label: 'After dialysis in double lumen', value: MedicationFrequencyEnum.AfterDialysisInDoubleLumen },
    { label: 'At the start of dialysis', value: MedicationFrequencyEnum.AtTheStartOfDialysis },
    { label: 'During dialysis', value: MedicationFrequencyEnum.DuringDialysis },
    { label: 'Before dialysis', value: MedicationFrequencyEnum.BeforeDialysis },
    {
      label: 'First injection now, then after 1 month, next at 2 months end, 3rd injection at 6 months end',
      value: MedicationFrequencyEnum.FirstInjectionNowThenAfter1MonthNextAt2MonthsEnd3rdInjectionAt6MonthsEnd,
    },
    { label: 'Once in a year', value: MedicationFrequencyEnum.OnceInAYear },
    { label: 'One injection now, next after a month', value: MedicationFrequencyEnum.OneInjectionNowNextAfterAMonth },
    {
      label: 'One injection now, one after a month, next after 6 months',
      value: MedicationFrequencyEnum.OneInjectionNowOneAfterAMonthNextAfter6Months,
    },
  ] ;
  
  