export enum MedicationInstructionEnum {
    BeforeBreakfast = 1,
    AfterBreakfast = 2,
    BeforeDinner = 3,
    AfterDinner = 4,
    EmptyStomach = 5,
    AtBedtime = 6,
    Immediately = 7,
    BeforeLunch = 8,
    AfterLunch = 9,
    BeforeMeal = 10,
    AfterMeal = 11,
    WhenRequired = 12,
    AsNeeded = 13,
    EverySixHours = 14,
    EveryFourHours = 15,
    EveryTwoHours = 16,
    EveryOneHour = 17,
    EveryOtherDay = 18,
    EveryTwoWeeks = 19,
    ThreeTimesAWeek = 20,
    TwoTimesAWeek = 21,
    OnceAWeek = 22,
    OnceAMonth = 23,
    OnceInTwoMonths = 24,
    OnceInThreeMonths = 25,
    ForItching = 26,
    ForSleep = 27,
    ForImprovingBloodDeficiency = 28,
    ForKidneys = 29,
    ForBreathingDifficulty = 30,
    ForKeepingCalm = 31,
    ForTransplant = 32,
    ForDiabetes = 33,
    ForBloodPressure = 34,
    ForDiarrhea = 35,
    ForSwelling = 36,
    ForMuscles = 37,
    ForNerves = 38,
    ForChestInfection = 39,
    ForPain = 40,
    ForIncreasingUrine = 41,
    ForIncreasingAppetite = 42,
    PRN = 43,
    ForIncreasingImmunity = 44,
    ForLightPain = 45,
    ForAbdominalGas = 46,
    STAT = 47,
    ForStomach = 48,
    ForSeverePain = 49,
    ForJointPain = 50,
    ForJoints = 51,
    ForUricAcid = 52,
    ForThyroid = 53,
    ForBladder = 54,
    ToKeepCalm = 55,
    ForFever = 56,
    ForMusclePain = 57,
    ForMuscleStrain = 58,
    SteroidMedicine = 59,
    ForStrengthOfJoints = 60,
    ToPreventUricAcidEffects = 61,
    ToReduceInflamation = 62,
    ToPreventFits = 63,
    ForBoneStrength = 64,
    BeforeDialysis = 65,
    AfterDialysis = 66,
    DuringDialysis = 67,
    AtTheStartOfDialysis = 68,
    ForHeadache = 69,
    ForPainInStomach = 70,
    ForAbdominalBloating = 71,
    ForBurningInChest = 72,
    ForChestPain = 73,
    VaccineToPreventHepatitisB = 74,
    VaccineToPreventFlu = 75,
    VaccineForPneumonia = 76,
    VaccineToPreventMeningitis = 77,
  }
  
export  const MedicationInstructions: Array<{label: string, value: MedicationInstructionEnum}> = [
    { label: 'BeforeBreakfast', value: MedicationInstructionEnum.BeforeBreakfast },
    { label: 'AfterBreakfast', value: MedicationInstructionEnum.AfterBreakfast },
    { label: 'BeforeDinner', value: MedicationInstructionEnum.BeforeDinner },
    { label: 'AfterDinner', value: MedicationInstructionEnum.AfterDinner },
    { label: 'EmptyStomach', value: MedicationInstructionEnum.EmptyStomach },
    { label: 'AtBedtime', value: MedicationInstructionEnum.AtBedtime },
    { label: 'Immediately', value: MedicationInstructionEnum.Immediately },
    { label: 'BeforeLunch', value: MedicationInstructionEnum.BeforeLunch },
    { label: 'AfterLunch', value: MedicationInstructionEnum.AfterLunch },
    { label: 'BeforeMeal', value: MedicationInstructionEnum.BeforeMeal },
    { label: 'AfterMeal', value: MedicationInstructionEnum.AfterMeal },
    { label: 'WhenRequired', value: MedicationInstructionEnum.WhenRequired },
    { label: 'AsNeeded', value: MedicationInstructionEnum.AsNeeded },
    { label: 'EverySixHours', value: MedicationInstructionEnum.EverySixHours },
    { label: 'EveryFourHours', value: MedicationInstructionEnum.EveryFourHours },
    { label: 'EveryTwoHours', value: MedicationInstructionEnum.EveryTwoHours },
    { label: 'EveryOneHour', value: MedicationInstructionEnum.EveryOneHour },
    { label: 'EveryOtherDay', value: MedicationInstructionEnum.EveryOtherDay },
    { label: 'EveryTwoWeeks', value: MedicationInstructionEnum.EveryTwoWeeks },
    { label: 'ThreeTimesAWeek', value: MedicationInstructionEnum.ThreeTimesAWeek },
    { label: 'TwoTimesAWeek', value: MedicationInstructionEnum.TwoTimesAWeek },
    { label: 'OnceAWeek', value: MedicationInstructionEnum.OnceAWeek },
    { label: 'OnceAMonth', value: MedicationInstructionEnum.OnceAMonth },
    { label: 'OnceInTwoMonths', value: MedicationInstructionEnum.OnceInTwoMonths },
    { label: 'OnceInThreeMonths', value: MedicationInstructionEnum.OnceInThreeMonths },
    { label: 'ForItching', value: MedicationInstructionEnum.ForItching },
    { label: 'ForSleep', value: MedicationInstructionEnum.ForSleep },
    { label: 'ForImprovingBloodDeficiency', value: MedicationInstructionEnum.ForImprovingBloodDeficiency },
    { label: 'ForKidneys', value: MedicationInstructionEnum.ForKidneys },
    { label: 'ForBreathingDifficulty', value: MedicationInstructionEnum.ForBreathingDifficulty },
    { label: 'ForKeepingCalm', value: MedicationInstructionEnum.ForKeepingCalm },
    { label: 'ForTransplant', value: MedicationInstructionEnum.ForTransplant },
    { label: 'ForDiabetes', value: MedicationInstructionEnum.ForDiabetes },
    { label: 'ForBloodPressure', value: MedicationInstructionEnum.ForBloodPressure },
    { label: 'ForDiarrhea', value: MedicationInstructionEnum.ForDiarrhea },
    { label: 'ForSwelling', value: MedicationInstructionEnum.ForSwelling },
    { label: 'ForMuscles', value: MedicationInstructionEnum.ForMuscles },
    { label: 'ForNerves', value: MedicationInstructionEnum.ForNerves },
    { label: 'ForChestInfection', value: MedicationInstructionEnum.ForChestInfection },
    { label: 'ForPain', value: MedicationInstructionEnum.ForPain },
    { label: 'ForIncreasingUrine', value: MedicationInstructionEnum.ForIncreasingUrine },
    { label: 'ForIncreasingAppetite', value: MedicationInstructionEnum.ForIncreasingAppetite },
    { label: 'PRN', value: MedicationInstructionEnum.PRN },
    { label: 'ForIncreasingImmunity', value: MedicationInstructionEnum.ForIncreasingImmunity },
    { label: 'ForLightPain', value: MedicationInstructionEnum.ForLightPain },
    { label: 'ForAbdominalGas', value: MedicationInstructionEnum.ForAbdominalGas },
    { label: 'STAT', value: MedicationInstructionEnum.STAT },
    { label: 'ForStomach', value: MedicationInstructionEnum.ForStomach },
    { label: 'ForSeverePain', value: MedicationInstructionEnum.ForSeverePain },
    { label: 'ForJointPain', value: MedicationInstructionEnum.ForJointPain },
    { label: 'ForJoints', value: MedicationInstructionEnum.ForJoints },
    { label: 'ForUricAcid', value: MedicationInstructionEnum.ForUricAcid },
    { label: 'ForThyroid', value: MedicationInstructionEnum.ForThyroid },
    { label: 'ForBladder', value: MedicationInstructionEnum.ForBladder },
    { label: 'ToKeepCalm', value: MedicationInstructionEnum.ToKeepCalm },
    { label: 'ForFever', value: MedicationInstructionEnum.ForFever },
    { label: 'ForMusclePain', value: MedicationInstructionEnum.ForMusclePain },
    { label: 'ForMuscleStrain', value: MedicationInstructionEnum.ForMuscleStrain },
    { label: 'SteroidMedicine', value: MedicationInstructionEnum.SteroidMedicine },
    { label: 'ForStrengthOfJoints', value: MedicationInstructionEnum.ForStrengthOfJoints },
    { label: 'ToPreventUricAcidEffects', value: MedicationInstructionEnum.ToPreventUricAcidEffects },
    { label: 'ToReduceInflamation', value: MedicationInstructionEnum.ToReduceInflamation },
    { label: 'ToPreventFits', value: MedicationInstructionEnum.ToPreventFits },
    { label: 'ForBoneStrength', value: MedicationInstructionEnum.ForBoneStrength },
    { label: 'BeforeDialysis', value: MedicationInstructionEnum.BeforeDialysis },
    { label: 'AfterDialysis', value: MedicationInstructionEnum.AfterDialysis },
    { label: 'DuringDialysis', value: MedicationInstructionEnum.DuringDialysis },
    { label: 'AtTheStartOfDialysis', value: MedicationInstructionEnum.AtTheStartOfDialysis },
    { label: 'ForHeadache', value: MedicationInstructionEnum.ForHeadache },
    { label: 'ForPainInStomach', value: MedicationInstructionEnum.ForPainInStomach },
    { label: 'ForAbdominalBloating', value: MedicationInstructionEnum.ForAbdominalBloating },
    { label: 'ForBurningInChest', value: MedicationInstructionEnum.ForBurningInChest },
    { label: 'ForChestPain', value: MedicationInstructionEnum.ForChestPain },
    { label: 'VaccineToPreventHepatitisB', value: MedicationInstructionEnum.VaccineToPreventHepatitisB },
    { label: 'VaccineToPreventFlu', value: MedicationInstructionEnum.VaccineToPreventFlu },
    { label: 'VaccineForPneumonia', value: MedicationInstructionEnum.VaccineForPneumonia },
    { label: 'VaccineToPreventMeningitis', value: MedicationInstructionEnum.VaccineToPreventMeningitis },
  ];
  