export enum BaseEndPoints {
    User = 'user',
    Patient = 'patient',
    Token = 'token',
    Messages = 'message',
    Account = 'account',
    Medicine = 'medicine',
    Medication = 'medication',
    Test = 'labtest',
    Patienttestinvoice = 'patienttestinvoice',
    PatientSample = 'patientsample',
    Patienttestinvoiceitem = 'patienttestinvoiceitem',
    Patientsamplereport = 'patientsamplereport',
    Category = 'labtestcategory',
    Appointment = 'appointment',
    Doctor = 'doctor',
    Prescription = 'prescription',
    Vitals = 'vital',
    Vendor = 'vendor',
    Medicinebrand = 'medicinebrand',
    LabOrder = 'laborder',
    MeicinePurchase = 'medicinepurchase',
    MeicineSale = 'medicinesale',
    Scheduling = 'schedule',
    FileAttachment = 'patientattachment',
    PatientVisit = 'patientvisit',
    HealthRecord = 'healthrecord'
}
