export enum BaseEndPoints {
    User = 'user',
    Patient = 'patient',
    Token = 'token',
    Messages = 'message',
    Account = 'account',
    Medicine = 'medicine',
    Medication = 'medication',
    Test = 'labtest',
    Patienttestinvoice = 'patienttestinvoice',
    PatientSample = 'patientsample',
    Patienttestinvoiceitem = 'patienttestinvoiceitem',
    Category = 'labtestcategory',
    Appointment = 'appointment',
    Doctor = 'doctor',
    Prescription = 'prescription',
    Vitals = 'vitals',
    Vendor = 'vendor',
    LabOrder = 'laborder'
}
